//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackSazerak.Editor.lib.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MODEXngine.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Games.
        /// </summary>
        public static string About_AvailableGames {
            get {
                return ResourceManager.GetString("About_AvailableGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Renderers.
        /// </summary>
        public static string About_AvailableRenderers {
            get {
                return ResourceManager.GetString("About_AvailableRenderers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Jarred Capellman.
        /// </summary>
        public static string About_CreatedBy {
            get {
                return ResourceManager.GetString("About_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Games Available.
        /// </summary>
        public static string About_NoAvailableGames {
            get {
                return ResourceManager.GetString("About_NoAvailableGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Renderers Available.
        /// </summary>
        public static string About_NoAvailableRenderers {
            get {
                return ResourceManager.GetString("About_NoAvailableRenderers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Data Directory Path.
        /// </summary>
        public static string GameSelection_GameDirectoryPath {
            get {
                return ResourceManager.GetString("GameSelection_GameDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string GameSelection_LabelGame {
            get {
                return ResourceManager.GetString("GameSelection_LabelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game.
        /// </summary>
        public static string GameSelection_LaunchGame {
            get {
                return ResourceManager.GetString("GameSelection_LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Games Available.
        /// </summary>
        public static string GameSelection_NoGamesAvailable {
            get {
                return ResourceManager.GetString("GameSelection_NoGamesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer was not found, please check your install.
        /// </summary>
        public static string GameSelection_RendererNotFound {
            get {
                return ResourceManager.GetString("GameSelection_RendererNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GameSelection_SelectGameDataPath {
            get {
                return ResourceManager.GetString("GameSelection_SelectGameDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GameSelection_Title {
            get {
                return ResourceManager.GetString("GameSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Global_Ok {
            get {
                return ResourceManager.GetString("Global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Settings_LabelFullScreen {
            get {
                return ResourceManager.GetString("Settings_LabelFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer.
        /// </summary>
        public static string Settings_LabelRenderer {
            get {
                return ResourceManager.GetString("Settings_LabelRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Settings_LabelResolution {
            get {
                return ResourceManager.GetString("Settings_LabelResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Enabled.
        /// </summary>
        public static string Settings_LabelSoundEnabled {
            get {
                return ResourceManager.GetString("Settings_LabelSoundEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Renderers Available.
        /// </summary>
        public static string Settings_NoRenderersAvailable {
            get {
                return ResourceManager.GetString("Settings_NoRenderersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
